import type { PdfSection } from '../types';

export interface AllFeaturesData {
  generatedDate?: string;
}

const FEATURE_CATEGORIES: { category: string; description: string; features: { name: string; detail: string }[] }[] = [
  {
    category: 'Clinical Documentation',
    description: 'Complete clinical note creation, AI assistance, and documentation workflow tools',
    features: [
      { name: 'AI-Assisted SOAP Note Generation', detail: 'Auto-generate structured SOAP notes from clinical context using AI' },
      { name: 'Ambient Voice Transcription', detail: 'Hands-free real-time dictation converted to structured clinical notes' },
      { name: 'Guided Note Mode', detail: 'Step-by-step structured note entry with smart prompts and clinical logic' },
      { name: 'Traditional Free-Text Note Mode', detail: 'Standard narrative note entry with rich text formatting' },
      { name: '100+ Clinical Templates', detail: 'Pre-built templates for all specialties including primary care, psychiatry, cardiology, and more' },
      { name: '500+ Smart Phrases & Snippets', detail: 'Customizable text expansion library for rapid documentation' },
      { name: 'Documentation Quality Scoring', detail: 'Real-time compliance scoring against E/M guidelines and payer requirements' },
      { name: 'MDM Complexity Calculator', detail: 'Automated medical decision-making level calculation for correct billing' },
      { name: 'Ghost Note Engine', detail: 'AI-suggested content based on patient history and visit context' },
      { name: 'Note Co-Signing & Attestation', detail: 'Cosigner workflow for residents, mid-levels, and student notes' },
      { name: 'Note Revision History', detail: 'Full audit trail of all note edits with timestamped versions' },
      { name: 'Addendum Support', detail: 'Append corrections or additions to finalized notes' },
      { name: 'Note Void & Deletion', detail: 'HIPAA-compliant note voiding with reason tracking' },
      { name: 'Inline CDS Nudges', detail: 'Evidence-based clinical decision support alerts embedded in the note editor' },
      { name: 'AI Draft Panel', detail: 'Side-by-side AI suggestion panel during note creation' },
      { name: 'Chart Print & PDF Export', detail: 'Generate formatted PDF printouts of any note or full chart' },
      { name: 'SmartPhrases Editor', detail: 'Create, manage, and share custom smart phrase library across providers' },
    ],
  },
  {
    category: 'AI & Clinical Intelligence',
    description: 'Advanced artificial intelligence tools for clinical support, risk stratification, and decision support',
    features: [
      { name: 'AI Clinical Copilot Sidebar', detail: 'Real-time AI intelligence panel with patient context and suggestions' },
      { name: 'Differential Diagnosis Support', detail: 'AI-powered differential diagnosis generation from symptoms and findings' },
      { name: 'HCC Risk Coding Assistant', detail: 'Identifies Hierarchical Condition Category codes to maximize risk adjustment' },
      { name: 'Smart Chart Pre-Brief', detail: 'Automated pre-visit summary of key clinical issues and action items' },
      { name: 'Visit Quality Scoring', detail: 'AI scores each visit for completeness, compliance, and coding accuracy' },
      { name: 'Second Brain Patient Memory', detail: 'Persistent AI memory of patient history, patterns, and clinical context' },
      { name: 'Care Narrative Panel', detail: 'AI-generated longitudinal patient story for rapid context during visits' },
      { name: 'Symptom Pattern Recognition', detail: 'AI identifies recurring symptom patterns and flags clinical trends' },
      { name: 'Predictive No-Show Engine', detail: 'ML-based appointment no-show risk prediction for proactive outreach' },
      { name: 'Risk Scenario Modeling', detail: 'AI models potential clinical risk scenarios based on patient data' },
      { name: 'Clinical Context Reminders', detail: 'AI-generated visit preparation reminders from prior encounters' },
      { name: 'Smart Encounter Prep', detail: 'Automated pre-visit checklist with outstanding items and gap closures' },
      { name: 'AI Document Analyzer', detail: 'Extracts structured data from uploaded clinical documents via AI' },
      { name: 'AI Fax Processing', detail: 'Auto-categorizes and routes incoming faxes using document AI' },
      { name: 'Adaptive Documentation AI', detail: 'AI learns provider preferences over time to improve note suggestions' },
    ],
  },
  {
    category: 'Patient Management',
    description: 'Complete patient registration, demographics, and clinical record management',
    features: [
      { name: 'Patient Registration & Demographics', detail: 'Full patient profile with demographics, contact info, and identifiers' },
      { name: 'Problem List with ICD-10 Codes', detail: 'Structured problem list linked to searchable ICD-10 code database' },
      { name: 'Medication Management & Reconciliation', detail: 'Active medication list with reconciliation workflows at transitions of care' },
      { name: 'Allergy Tracking with Severity', detail: 'Allergy and adverse reaction list with severity levels and cross-sensitivity alerts' },
      { name: 'Vital Signs Recording & Trending', detail: 'Multi-parameter vitals capture with historical trending graphs' },
      { name: 'Duplicate Patient Detection', detail: 'AI-powered duplicate detection prevents redundant chart creation' },
      { name: 'Patient Staging Board', detail: 'Kanban-style workflow board for tracking patient care status' },
      { name: 'Patient Quick View', detail: 'Compact summary panel for rapid chart review without opening full chart' },
      { name: 'Patient Risk Dashboard', detail: 'Composite risk scores and risk factor visualization for panel management' },
      { name: 'Patient Activity Log', detail: 'Complete audit trail of all patient chart interactions' },
      { name: 'Patient Photo Management', detail: 'Secure photo capture and storage for patient identification' },
      { name: 'Advance Directives Tracking', detail: 'Record and manage advance directives, POLST, and healthcare proxies' },
      { name: 'Clinical Photography', detail: 'Secure wound care, dermatology, and progress photo documentation' },
      { name: 'Patient Search Autocomplete', detail: 'Fast phonetic and partial-name patient lookup across all records' },
    ],
  },
  {
    category: 'Scheduling & Appointments',
    description: 'Full-featured appointment scheduling, calendar management, and scheduling intelligence',
    features: [
      { name: 'Multi-Provider Calendar Views', detail: 'Day, week, and month views with side-by-side provider comparison' },
      { name: 'Drag-and-Drop Appointment Management', detail: 'Intuitive appointment rescheduling via drag-and-drop interface' },
      { name: 'Provider Availability Templates', detail: 'Recurring schedule templates with block time and special hours' },
      { name: 'Recurring Appointments', detail: 'Set appointment series with automatic recurrence scheduling' },
      { name: 'Appointment Request & Approval', detail: 'Patient-submitted appointment requests with staff review workflow' },
      { name: 'Public Patient Self-Scheduling', detail: 'Patient-facing booking page with real-time availability' },
      { name: 'Waitlist Management', detail: 'Auto-fill cancelled slots from waitlist with patient notification' },
      { name: 'Patient Check-In System', detail: 'Digital check-in with photo capture and form completion' },
      { name: 'Scheduling Notification Rules', detail: 'Configurable automated reminders, confirmations, and follow-up messages' },
      { name: 'Scheduling Intelligence Dashboard', detail: 'Analytics on utilization, no-shows, and scheduling efficiency' },
      { name: 'Missed Appointment Follow-Up', detail: 'Automated outreach workflows for no-shows and cancellations' },
      { name: 'Appointment Waitlist Auto-Match', detail: 'Intelligently matches waitlisted patients to newly opened slots' },
    ],
  },
  {
    category: 'Billing & Revenue Cycle Management',
    description: 'End-to-end billing automation from charge capture through payment posting and denial management',
    features: [
      { name: 'CMS-1500 & X12 837P Claim Generation', detail: 'Automated claim creation from encounter data with full EDI compliance' },
      { name: 'Batch Claim Submission', detail: 'Submit hundreds of claims simultaneously with status tracking' },
      { name: 'AI Claim Scrubber', detail: 'Pre-submission AI review catches NCCI edits, bundling, and payer-specific rules' },
      { name: 'ERA/835 Auto-Posting', detail: 'Electronic remittance advice auto-posting with exception handling' },
      { name: 'Secondary Claims Automation', detail: 'Automatic secondary payer claim generation after primary adjudication' },
      { name: 'Denial Management & Appeals', detail: 'Denial tracking, root cause analysis, and automated appeal letter generation' },
      { name: 'Fee Schedule Management', detail: 'Multi-payer fee schedule upload, comparison, and underpayment detection' },
      { name: 'Patient Billing & Statements', detail: 'Patient-friendly billing statements with payment portal integration' },
      { name: 'Payment Plans Manager', detail: 'Structured payment plan creation with automated payment collection' },
      { name: 'Claim.MD Integration', detail: 'Direct integration with Claim.MD clearinghouse for claim submission and ERAs' },
      { name: 'Office Ally EDI Integration', detail: 'Full Office Ally clearinghouse connectivity via SOAP, SFTP, and MIME' },
      { name: 'Express Payment Posting', detail: 'Rapid manual payment posting with bulk entry tools' },
      { name: 'Charge Capture & Superbill', detail: 'Point-of-care charge capture with CPT/ICD-10 code lookup' },
      { name: 'Simplified Billing Dashboard', detail: 'Streamlined billing view for practices without full RCM complexity' },
      { name: 'Financial Aging Dashboard', detail: 'Receivables aging analysis by payer, provider, and date range' },
      { name: 'Revenue Cycle Intelligence', detail: 'AI-driven RCM analytics with actionable revenue optimization insights' },
      { name: 'RCM Pipeline', detail: 'Visual pipeline tracking claims from submission through payment' },
      { name: 'QuickBooks Export', detail: 'Financial data export in QuickBooks-compatible format' },
    ],
  },
  {
    category: 'Prescriptions & Medications',
    description: 'Full prescription management for all medication types',
    features: [
      { name: 'Electronic Prescription Transmission', detail: 'NCPDP-certified electronic prescription transmission to any US pharmacy' },
      { name: 'Drug Search (80,000+ Medications)', detail: 'Comprehensive drug database with brand, generic, and compound options' },
      { name: 'Pharmacy Search & Directory', detail: 'Real-time pharmacy lookup by location and network' },
      { name: 'Drug Interaction Checking', detail: 'Multi-drug interaction alerts with severity classification' },
      { name: 'Allergy Cross-Reference Alerts', detail: 'Automated allergy checking against prescribed medications' },
      { name: 'Formulary Checking', detail: 'Insurance formulary verification with tier pricing and alternatives' },
      { name: 'Prescription History', detail: 'Complete prescription history with Rx refill tracking' },
      { name: 'Medication Reconciliation', detail: 'Structured medication reconciliation workflow at care transitions' },
      { name: 'Refill Request Manager', detail: 'Streamlined pharmacy refill request handling and approval' },
      { name: 'Controlled Substance Prescribing', detail: 'DEA-compliant prescribing for Schedule II-V controlled substances' },
      { name: 'Medication Trial History', detail: 'Tracks past medication trials, responses, and discontinuation reasons' },
      { name: 'PDMP Check Integration', detail: 'Real-time Prescription Drug Monitoring Program query integration' },
      { name: 'Patient Preferred Pharmacy', detail: 'Store and default to patient-preferred pharmacies for prescriptions' },
    ],
  },
  {
    category: 'Telehealth & Video Visits',
    description: 'HIPAA-compliant video visits and virtual care powered by Twilio Video',
    features: [
      { name: 'Twilio HD Video Visits', detail: 'HIPAA-eligible HD video sessions with zero software install required' },
      { name: 'Virtual Waiting Room', detail: 'Patient-facing waiting room with tech check and arrival notification' },
      { name: 'Patient Join Page', detail: 'Simplified patient-facing entry point with link-based access' },
      { name: 'Telehealth Chart Panel', detail: 'Side-by-side chart access during active video sessions' },
      { name: 'Group Therapy Sessions', detail: 'Multi-participant video sessions for group therapy and team care' },
      { name: 'Async Telehealth', detail: 'Store-and-forward asynchronous video and photo consultations' },
      { name: 'Remote Patient Monitoring (RPM)', detail: 'Device-linked data collection with automated billing for RPM codes' },
      { name: 'Telehealth Billing Enhancement', detail: 'Automated telehealth-specific billing code selection and documentation' },
      { name: 'Telehealth Consent Management', detail: 'Digital consent capture and storage for telehealth encounters' },
      { name: 'Telehealth Appointments View', detail: 'Dedicated calendar view for upcoming and past telehealth encounters' },
      { name: 'Start Visit Modal', detail: 'One-click visit launch with patient and provider link generation' },
    ],
  },
  {
    category: 'Patient Portal & Engagement',
    description: 'Full-featured patient-facing portal for self-service, communication, and engagement',
    features: [
      { name: 'Patient Self-Scheduling', detail: 'Patients book, reschedule, and cancel appointments online 24/7' },
      { name: 'Lab Results Access', detail: 'Patients view lab results with provider interpretation notes' },
      { name: 'Visit Summaries & After-Visit Notes', detail: 'Auto-generated after-visit summaries delivered to patient portal' },
      { name: 'Secure Patient Messaging', detail: 'HIPAA-compliant two-way messaging between patients and care team' },
      { name: 'Online Bill Pay', detail: 'Patients pay outstanding balances via Stripe-powered portal' },
      { name: 'Digital Intake Forms', detail: 'Pre-visit electronic intake with configurable clinical and administrative fields' },
      { name: 'Medication Refill Requests', detail: 'Patients request medication refills through the portal' },
      { name: 'Family Accounts & Caregiver Access', detail: 'Family member proxy access for dependent management' },
      { name: 'Patient Education Library', detail: '300+ searchable patient education materials by diagnosis' },
      { name: 'Appointment Reminders', detail: 'Automated SMS and email reminders with configurable timing' },
      { name: 'Portal Invitation System', detail: 'Automated patient portal invitation with registration workflow' },
      { name: 'Symptom Triage Chatbot', detail: 'AI-powered pre-visit symptom assessment chatbot in portal' },
      { name: 'Pre-Visit Check-In', detail: 'Digital check-in with form completion before arrival' },
      { name: 'Patient Cost Estimator', detail: 'Pre-visit cost estimation based on insurance and service type' },
    ],
  },
  {
    category: 'Assessments & Screenings',
    description: 'Standardized clinical assessments, screening tools, and behavioral health instruments',
    features: [
      { name: 'PHQ-9 Depression Screening', detail: 'Validated 9-item patient health questionnaire for depression severity' },
      { name: 'GAD-7 Anxiety Screening', detail: 'Generalized anxiety disorder 7-item scale with severity scoring' },
      { name: 'PHQ-2 Brief Depression Screen', detail: 'Two-question depression screener for rapid assessment' },
      { name: 'AUDIT Alcohol Use Screening', detail: 'Alcohol Use Disorders Identification Test with risk stratification' },
      { name: 'DAST-10 Drug Abuse Screening', detail: 'Drug Abuse Screening Test for substance use disorder assessment' },
      { name: 'CAGE-AID Screening', detail: 'CAGE Adapted to Include Drugs questionnaire' },
      { name: 'PCL-5 PTSD Checklist', detail: 'DSM-5 PTSD symptom checklist for trauma assessment' },
      { name: 'Columbia Suicide Severity Rating', detail: 'Validated suicide risk assessment and safety planning tool' },
      { name: 'Functional Assessment (WHODAS)', detail: 'WHO Disability Assessment Schedule for functional status' },
      { name: 'SDOH Screening', detail: 'Social Determinants of Health screening with referral integration' },
      { name: 'SBIRT Screening', detail: 'Screening, Brief Intervention, and Referral to Treatment protocol' },
      { name: 'Pediatric Growth Charts', detail: 'CDC/WHO growth chart plotting with percentile calculations' },
      { name: '50+ Assessment Templates', detail: 'Full library of validated clinical instruments across all specialties' },
      { name: 'Assessment Group Manager', detail: 'Group assessments into protocols for consistent administration' },
      { name: 'Assessment Frequency Scheduling', detail: 'Schedule recurring assessments with automated patient reminders' },
      { name: 'Assessment Session Scoring', detail: 'Automatic scoring with clinical interpretation and trending' },
    ],
  },
  {
    category: 'CCM & Chronic Care Management',
    description: 'Complete Chronic Care Management module for 99490/99439 billing and population management',
    features: [
      { name: 'CCM Patient Panel', detail: 'Enrolled CCM patient list with monthly minute tracking' },
      { name: 'CCM Time Tracking', detail: 'Automatic and manual time logging against CCM billing thresholds' },
      { name: 'CCM Care Plan Editor', detail: 'CMS-compliant CCM care plan creation and management' },
      { name: 'CCM Monthly Packet', detail: 'Auto-generated monthly CCM documentation packet for billing' },
      { name: 'CCM Billing Readiness Report', detail: 'Real-time report of which patients are ready to bill for the month' },
      { name: 'CCM Enrollment Modal', detail: 'Streamlined patient enrollment workflow with consent capture' },
      { name: 'CCM Patient Check-In', detail: 'Monthly check-in workflow with templated clinical questions' },
      { name: 'CCM Outreach Scheduler', detail: 'Automated patient outreach scheduling for monthly care calls' },
      { name: 'CCM Review Inbox', detail: 'Review queue for pending CCM documentation and approvals' },
      { name: 'CCM Timer Widget', detail: 'Floating real-time timer for tracking CCM service minutes' },
      { name: 'RPM Billing Engine', detail: 'Remote Patient Monitoring billing calculation for CPT 99453-99458' },
    ],
  },
  {
    category: 'Prior Authorization',
    description: 'Comprehensive prior authorization management with AI-assisted documentation',
    features: [
      { name: 'Prior Auth Dashboard', detail: 'Central hub for all prior authorization requests and statuses' },
      { name: 'Prior Auth Wizard', detail: 'Guided workflow for creating complete prior authorization packets' },
      { name: 'AI Medical Necessity Letter', detail: 'AI-generated medical necessity letters tailored to payer requirements' },
      { name: 'Prior Auth Chart Extractor', detail: 'Auto-extracts supporting clinical data from chart for PA submission' },
      { name: 'Payer-Specific Form Builder', detail: 'Pre-configured forms for major payer PA requirements' },
      { name: 'Prior Auth Status Timeline', detail: 'Visual timeline tracking PA from submission through determination' },
      { name: 'Prior Auth Appeal Tab', detail: 'Structured appeal workflow with AI-generated appeal letters' },
      { name: 'Specialty PA Kits', detail: 'Pre-built documentation kits for common specialty medications' },
      { name: 'PA Performance Scorecard', detail: 'Analytics on PA approval rates, turnaround times, and denial reasons' },
      { name: 'PA FHIR Hub', detail: 'FHIR-based electronic PA exchange with participating payers' },
      { name: 'Medication Trial History Panel', detail: 'Tracks failed medication trials required for PA step therapy' },
    ],
  },
  {
    category: 'Laboratory & Orders',
    description: 'Lab ordering, results management, and clinical order set tools',
    features: [
      { name: 'Lab Order Entry (500+ Tests)', detail: 'Searchable lab catalog with 500+ tests and panels' },
      { name: 'Lab Results Trending', detail: 'Time-series graphs for key lab values across multiple encounters' },
      { name: 'Critical Lab Alerts', detail: 'Automated critical value alerting with acknowledgment workflow' },
      { name: 'AI Lab Fax Processing', detail: 'Incoming lab fax auto-matched to patients and structured into results' },
      { name: 'Lab Requisition Print', detail: 'Formatted lab requisition printout for non-electronic orders' },
      { name: 'Order Sets & Clinical Pathways', detail: 'Pre-built order sets for common diagnoses and conditions' },
      { name: 'Common Orders Catalog', detail: 'Practice-curated quick-order catalog for frequently used tests' },
      { name: 'Patient Orders Tracker', detail: 'Pending and completed orders tracking across all encounter types' },
      { name: 'Manual Lab Processing', detail: 'Manual entry of lab results received outside electronic channels' },
    ],
  },
  {
    category: 'Administrative & Practice Management',
    description: 'Practice-wide administrative tools for operations, staff management, and reporting',
    features: [
      { name: 'Role-Based Access Control (5 Roles)', detail: 'Granular permissions for provider, MA, front desk, biller, and admin' },
      { name: 'Staff Management & Profiles', detail: 'Staff directory, credential tracking, and profile management' },
      { name: 'Time Clock & Time Tracking', detail: 'Employee clock-in/out with payroll-ready time reports' },
      { name: 'Task Manager', detail: 'Assign, track, and complete clinical and administrative tasks' },
      { name: 'Smart Task Router', detail: 'AI-powered automatic task assignment based on role and workload' },
      { name: 'Workforce Scheduling', detail: 'Staff schedule management with shift planning and coverage tracking' },
      { name: 'Practice Admin Configuration', detail: 'Comprehensive practice settings for hours, providers, and services' },
      { name: 'Organization Multi-Tenancy', detail: 'Complete data isolation for multi-location and multi-organization deployments' },
      { name: 'Audit Logs', detail: 'Comprehensive activity logging for HIPAA compliance and security monitoring' },
      { name: 'Admin Change Audit Log', detail: 'Detailed tracking of all administrative configuration changes' },
      { name: 'Batch Operations Center', detail: 'Bulk processing for claims, messages, eligibility, and other tasks' },
      { name: 'Practice Usage Reports', detail: 'Utilization reports for providers, staff, and system features' },
    ],
  },
  {
    category: 'Communications & Messaging',
    description: 'Integrated SMS, email, secure messaging, and fax communication tools',
    features: [
      { name: 'Two-Way SMS Messaging', detail: 'HIPAA-compliant two-way SMS with patients and contacts' },
      { name: 'SMS Broadcast Campaigns', detail: 'Targeted patient population SMS campaigns with compliance tracking' },
      { name: 'SMS Template Manager', detail: 'Reusable SMS templates for common outreach scenarios' },
      { name: 'Appointment Confirmations & Reminders', detail: 'Automated appointment confirmation and reminder messages via SMS/email' },
      { name: 'Care Team Messaging', detail: 'Internal HIPAA-compliant staff and care team messaging' },
      { name: 'Messages Hub', detail: 'Unified inbox for all patient and staff messages' },
      { name: 'Smart Inbox', detail: 'AI-triaged message inbox with priority sorting and routing suggestions' },
      { name: 'Patient Message Compose', detail: 'Structured patient message creation with template support' },
      { name: 'Smart Follow-Up System', detail: 'Automated follow-up message triggers based on clinical events' },
      { name: 'Fax Dashboard & Address Book', detail: 'Cloud fax send/receive with searchable provider address book' },
      { name: 'AI Fax Categorization', detail: 'Automatic fax classification and patient matching using AI' },
      { name: 'Email System Integration', detail: 'Transactional and marketing email via SendGrid with template management' },
      { name: 'Portal Notifications', detail: 'In-app and email portal notifications for patients' },
      { name: 'Unified Notification Center', detail: 'Central hub for all system and patient notifications' },
    ],
  },
  {
    category: 'Analytics & Reporting',
    description: 'Executive dashboards, KPI tracking, and data export tools for practice intelligence',
    features: [
      { name: 'Executive Dashboard', detail: 'High-level KPIs covering clinical, financial, and operational performance' },
      { name: 'Revenue Analytics & Forecasting', detail: 'Revenue trend analysis with predictive forecasting models' },
      { name: 'Provider Performance Metrics', detail: 'Per-provider productivity, quality, and efficiency metrics' },
      { name: 'Advanced Reporting Hub', detail: 'Custom report builder with multi-dimensional filtering and export' },
      { name: 'Financial Export Manager', detail: 'Structured financial data exports for accounting and payroll integration' },
      { name: 'Real-Time Operations Dashboard', detail: 'Live view of daily operations including check-ins, visits, and tasks' },
      { name: 'Predictive Insights Dashboard', detail: 'Forward-looking analytics using ML models on practice data' },
      { name: 'Patient Satisfaction Dashboard', detail: 'Patient experience metrics and satisfaction score tracking' },
      { name: 'Encounters Reporting', detail: 'Visit volume, type, and complexity reporting by date range and provider' },
      { name: 'Time Reports', detail: 'Staff time and activity reports for HR and billing purposes' },
      { name: 'BI & KPI Monitoring', detail: 'Business intelligence dashboards with configurable KPI thresholds and alerts' },
      { name: 'Website Analytics Dashboard', detail: 'Practice website and patient portal traffic analytics' },
    ],
  },
  {
    category: 'Population Health & Quality',
    description: 'Population management, care gap closure, and quality measure reporting',
    features: [
      { name: 'Population Health Dashboard', detail: 'Panel-level health insights with condition prevalence and risk stratification' },
      { name: 'Risk Stratification', detail: 'Patient risk scoring and tiering for targeted care management' },
      { name: 'Care Gap Identification', detail: 'Automated identification of preventive care and chronic disease care gaps' },
      { name: 'Care Gap Outreach Engine', detail: 'Automated patient outreach campaigns for care gap closure' },
      { name: 'MIPS/MACRA Dashboard', detail: 'Real-time MIPS performance scoring and reporting readiness' },
      { name: 'HEDIS Auto-Calculator', detail: 'Automated HEDIS measure calculation from clinical documentation' },
      { name: 'HEDIS Automation Dashboard', detail: 'Dashboards for HEDIS quality measure tracking and submission' },
      { name: 'eCQM Reporting', detail: 'Electronic Clinical Quality Measure data collection and export' },
      { name: 'Cohort Management', detail: 'Define and manage patient cohorts for population programs and research' },
      { name: 'Disease Registry', detail: 'Structured registry for chronic disease tracking across the patient panel' },
      { name: 'Preventive Health Tracking', detail: 'Overdue preventive service identification and scheduling prompts' },
      { name: 'ACO Performance Dashboard', detail: 'Accountable Care Organization performance metrics and benchmarking' },
    ],
  },
  {
    category: 'Credentialing & Compliance',
    description: 'Provider credentialing, license tracking, and payer enrollment management',
    features: [
      { name: 'License & Certification Tracking', detail: 'Centralized repository for all provider licenses with expiration monitoring' },
      { name: 'Payer Enrollment Management', detail: 'Track payer enrollment status, effective dates, and revalidation' },
      { name: 'Primary Source Verification', detail: 'Automated verification of credentials against primary sources' },
      { name: 'Multi-State License Tracker', detail: 'Manage licenses across multiple states with renewal date tracking' },
      { name: 'Credentialing Application Detail', detail: 'Detailed credentialing application management per provider' },
      { name: 'Credentialing Timeline', detail: 'Visual timeline of credentialing milestones and deadlines' },
      { name: 'CAQH Profile Manager', detail: 'Integration with CAQH ProView for credential data management' },
      { name: 'Credentialing Document Manager', detail: 'Secure storage and management of credentialing documents' },
      { name: 'Expiration Monitoring & Alerts', detail: 'Proactive alerts for expiring licenses, certifications, and enrollments' },
      { name: 'Credentialing Notification Center', detail: 'Centralized credentialing alerts and task notifications' },
      { name: 'Compliance Tracker', detail: 'HIPAA, OSHA, and regulatory compliance checklist management' },
      { name: 'Information Blocking Compliance', detail: 'ONC information blocking rule compliance monitoring and documentation' },
    ],
  },
  {
    category: 'Interoperability & Integration',
    description: 'HL7/FHIR standards, external data exchange, and third-party integration capabilities',
    features: [
      { name: 'HL7 FHIR R4 API Access', detail: 'Full FHIR R4 API for external app integration and data exchange' },
      { name: 'CCD/CCDA Generation & Import', detail: 'Generate and consume Consolidated Clinical Document Architecture documents' },
      { name: 'HIE Connectivity', detail: 'Health Information Exchange connection for regional data sharing' },
      { name: 'ADT Notifications', detail: 'Admission, Discharge, Transfer notifications for care coordination' },
      { name: 'SMART on FHIR App Launcher', detail: 'Launch SMART on FHIR compliant third-party clinical apps in context' },
      { name: 'PDEX Patient Access', detail: 'CMS Payer Data Exchange for patient-requested insurance data access' },
      { name: 'Electronic Case Reporting', detail: 'Automated electronic case reporting to public health authorities' },
      { name: 'eConsult Hub', detail: 'Electronic specialist consultation request and response platform' },
      { name: 'Claim.MD Clearinghouse Integration', detail: 'Full Claim.MD integration for claims, eligibility, and ERAs' },
      { name: 'Office Ally EDI Integration', detail: 'Office Ally integration via SOAP, SFTP, and MIME protocols' },
      { name: 'Twilio (SMS, Fax, Voice, Video)', detail: 'Twilio for all communications including SMS, fax, voice, and telehealth video' },
      { name: 'Stripe Payment Processing', detail: 'Stripe Connect for patient payments and subscription management' },
      { name: 'Integration Hub', detail: 'Central dashboard for all third-party integration status and management' },
    ],
  },
  {
    category: 'Security & HIPAA Compliance',
    description: 'Enterprise-grade security controls and full HIPAA compliance infrastructure',
    features: [
      { name: 'HIPAA-Compliant Infrastructure', detail: 'End-to-end encryption, BAA availability, and HIPAA-ready hosting' },
      { name: 'Multi-Tenant Data Isolation', detail: 'Row-level security ensures complete organizational data separation' },
      { name: 'Two-Factor Authentication (2FA)', detail: 'TOTP-based 2FA with enforcement options for high-privilege roles' },
      { name: 'Electronic Signatures (ESIGN Act)', detail: 'Legally valid electronic signatures for clinical and consent documents' },
      { name: 'Session Timeout & Security', detail: 'Configurable automatic session timeout with secure re-authentication' },
      { name: 'Failed Login Tracking', detail: 'Brute-force protection with account lockout after failed login attempts' },
      { name: 'Password Strength Enforcement', detail: 'Configurable password complexity requirements with strength indicator' },
      { name: 'Security Audit Console', detail: 'Real-time security event monitoring and threat detection dashboard' },
      { name: 'PHI Access Logging', detail: 'Comprehensive logging of all protected health information access' },
      { name: 'MFA Enforcement Console', detail: 'Admin controls to mandate MFA for all users or specific roles' },
      { name: 'Audit Report Generator', detail: 'Generate formatted HIPAA audit reports for compliance reviews' },
      { name: 'SUD Data Partitioning', detail: '42 CFR Part 2 compliant substance use disorder record segregation' },
      { name: 'Reproductive Health Partitioning', detail: 'Separate access controls for reproductive health data' },
    ],
  },
  {
    category: 'Behavioral Health',
    description: 'Specialized tools for mental health, psychiatry, and substance use disorder care',
    features: [
      { name: 'Safety Plan Builder', detail: 'Structured Stanley-Brown safety plan creation and patient sharing' },
      { name: 'Treatment Plan Tracker', detail: 'Evidence-based treatment plan management with goal tracking' },
      { name: 'MBC Tracking Dashboard', detail: 'Measurement-Based Care tracking with trend visualization' },
      { name: 'CoCM Workflow', detail: 'Collaborative Care Model workflow with registry and case manager tools' },
      { name: 'DTx Prescription Pad', detail: 'Digital Therapeutics prescription for evidence-based mental health apps' },
      { name: 'Psych Intelligence Panel', detail: 'AI-powered psychiatric assessment and longitudinal mood tracking' },
      { name: 'Mood Trajectory Timeline', detail: 'Visual timeline of patient mood scores across assessments' },
      { name: 'Medication Response History', detail: 'Tracks psychiatric medication effectiveness over time' },
      { name: 'Safety Plan Versioning', detail: 'Version history for safety plans with date-stamped changes' },
      { name: 'Trauma-Informed Flags', detail: 'Clinical flags to alert care team of trauma history and sensitivities' },
      { name: 'Group Therapy Manager', detail: 'Group therapy session scheduling, attendance, and documentation' },
      { name: 'SUDConsent Manager', detail: '42 CFR Part 2 compliant consent management for SUD records' },
      { name: 'SBIRT & SDOH Screening', detail: 'Integrated SBIRT and social determinants screening with referral tools' },
    ],
  },
  {
    category: 'Vault & Document Management',
    description: 'Secure document storage, versioning, and organization-wide file management',
    features: [
      { name: 'Document Vault', detail: 'Secure HIPAA-compliant file storage with folder organization' },
      { name: 'Document Versioning', detail: 'Track document versions with history and rollback capability' },
      { name: 'Document Request Forms', detail: 'Structured patient document requests with tracking and delivery' },
      { name: 'Legacy Document Upload', detail: 'Import and index historical paper records and legacy EHR documents' },
      { name: 'Patient Documents Manager', detail: 'Per-patient document library with type categorization' },
      { name: 'Folder Create & Management', detail: 'Custom folder hierarchy for organized document storage' },
      { name: 'Document Analyzer', detail: 'AI extraction of structured data from uploaded clinical documents' },
      { name: 'Billing Vault', detail: 'Secure storage for payer contracts, fee schedules, and billing documents' },
      { name: 'Contract Details & Network Directory', detail: 'Payer contract management with network participation tracking' },
    ],
  },
  {
    category: 'Subscription & Platform Management',
    description: 'Self-service subscription management, pricing tiers, and add-on marketplace',
    features: [
      { name: 'Three-Tier Subscription Model', detail: 'Starter, Professional, and Enterprise tiers with per-provider pricing' },
      { name: 'Add-On Marketplace', detail: '13+ modular add-ons purchasable individually or bundled in tiers' },
      { name: 'Chargebee Subscription Integration', detail: 'Chargebee-powered subscription billing and plan management' },
      { name: 'Subscription Analytics', detail: 'MRR, churn, trial conversion, and add-on adoption metrics' },
      { name: 'Tier Feature Matrix', detail: 'Transparent feature-to-tier mapping for all capabilities' },
      { name: 'Scheduled Plan Changes', detail: 'Schedule tier upgrades or downgrades to take effect at next renewal' },
      { name: '30-Day Free Trial', detail: 'Full-featured 30-day trial with no credit card required' },
      { name: 'Practice Signup Wizard', detail: 'Self-service organization registration and onboarding wizard' },
      { name: 'Organization Setup Wizard', detail: 'Guided configuration for new practice setup including providers and payers' },
    ],
  },
];

export function buildAllFeaturesSections(data: AllFeaturesData): PdfSection[] {
  const sections: PdfSection[] = [];
  const generatedDate = data.generatedDate || new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  sections.push({
    type: 'paragraph',
    text: `CareMetric AI is an all-in-one, AI-first Electronic Medical Record platform built for independent and specialty practices. This document provides a comprehensive catalog of every feature across all ${FEATURE_CATEGORIES.length} categories, covering the complete platform as of ${generatedDate}.`,
  });

  sections.push({
    type: 'keyValue',
    pairs: [
      { label: 'Platform Version', value: '6.0' },
      { label: 'Total Feature Categories', value: `${FEATURE_CATEGORIES.length}` },
      { label: 'Total Individual Features', value: `${FEATURE_CATEGORIES.reduce((acc, c) => acc + c.features.length, 0)}+` },
      { label: 'Document Generated', value: generatedDate },
      { label: 'Website', value: 'caremetric.ai' },
    ],
  });

  sections.push({ type: 'divider' });

  sections.push({ type: 'heading', level: 2, text: 'Table of Contents' });
  sections.push({
    type: 'list',
    ordered: true,
    items: FEATURE_CATEGORIES.map((c) => `${c.category} (${c.features.length} features)`),
  });

  for (const category of FEATURE_CATEGORIES) {
    sections.push({ type: 'divider' });
    sections.push({ type: 'heading', level: 2, text: category.category });
    sections.push({ type: 'paragraph', text: category.description });
    sections.push({
      type: 'table',
      headers: ['Feature', 'Description'],
      rows: category.features.map(f => [f.name, f.detail]),
    });
  }

  sections.push({ type: 'divider' });
  sections.push({ type: 'heading', level: 2, text: 'Subscription Tier Summary' });
  sections.push({
    type: 'table',
    headers: ['Capability', 'Starter', 'Professional', 'Enterprise'],
    rows: [
      ['Core EMR & Clinical Documentation', 'Included', 'Included', 'Included'],
      ['AI SOAP Note Generation', 'Included', 'Included', 'Included'],
      ['Scheduling & Telehealth (Twilio Video)', 'Included', 'Included', 'Included'],
      ['Prescription Management', 'Included', 'Included', 'Included'],
      ['CCM & Prior Authorization', 'Included', 'Included', 'Included'],
      ['50+ Assessments & SDOH Screening', 'Included', 'Included', 'Included'],
      ['Automated Claims Billing (RCM)', 'Add-On', 'Included', 'Included'],
      ['Care Management Suite', 'Add-On', 'Included', 'Included'],
      ['Workflow Automation', 'Add-On', 'Included', 'Included'],
      ['AI Clinical Copilot', 'Add-On', 'Add-On', 'Included'],
      ['Advanced Analytics & BI', 'Add-On', 'Add-On', 'Included'],
      ['HL7/FHIR Interoperability', 'Add-On', 'Add-On', 'Included'],
      ['Population Health & Quality', 'Add-On', 'Add-On', 'Included'],
      ['Provider Credentialing', 'Add-On', 'Add-On', 'Included'],
      ['Patient Portal', 'Add-On', 'Add-On', 'Available'],
      ['Fax Integration', 'Add-On', 'Add-On', 'Available'],
    ],
  });

  sections.push({ type: 'spacer' });
  sections.push({
    type: 'paragraph',
    text: 'CareMetric AI offers a 30-day free trial with full feature access. No credit card required. For custom enterprise pricing or questions, contact sales@caremetric.ai.',
    highlight: 'success',
  });

  return sections;
}
