import { StyleSheet } from '@react-pdf/renderer';

export const BRAND_COLORS = {
  primary: '#1a6ffa',
  primaryLight: '#3391ff',
  dark: '#132859',
  accent: '#0ea5e9',
  text: '#1f2937',
  textLight: '#6b7280',
  border: '#e5e7eb',
  bgLight: '#f3f4f6',
  white: '#ffffff',
  success: '#059669',
  warning: '#d97706',
  critical: '#dc2626',
};

export const pdfStyles = StyleSheet.create({
  page: {
    fontFamily: 'Helvetica',
    fontSize: 10,
    paddingTop: 80,
    paddingBottom: 60,
    paddingHorizontal: 40,
    color: BRAND_COLORS.text,
  },
  header: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 40,
    paddingTop: 16,
    paddingBottom: 12,
    borderBottomWidth: 2,
    borderBottomColor: BRAND_COLORS.primary,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  headerLogo: {
    width: 36,
    height: 36,
  },
  headerPracticeName: {
    fontSize: 12,
    fontFamily: 'Helvetica-Bold',
    color: BRAND_COLORS.dark,
  },
  headerAddress: {
    fontSize: 7,
    color: BRAND_COLORS.textLight,
    marginTop: 2,
  },
  headerRight: {
    alignItems: 'flex-end',
  },
  headerTitle: {
    fontSize: 11,
    fontFamily: 'Helvetica-Bold',
    color: BRAND_COLORS.primary,
  },
  headerDate: {
    fontSize: 7,
    color: BRAND_COLORS.textLight,
    marginTop: 2,
  },
  footer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 40,
    paddingBottom: 12,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: BRAND_COLORS.border,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  footerText: {
    fontSize: 6,
    color: BRAND_COLORS.textLight,
  },
  footerConfidential: {
    fontSize: 6,
    color: BRAND_COLORS.critical,
    fontFamily: 'Helvetica-Bold',
  },
  pageNumber: {
    fontSize: 7,
    color: BRAND_COLORS.textLight,
  },
  patientBar: {
    backgroundColor: BRAND_COLORS.bgLight,
    borderRadius: 4,
    padding: 8,
    marginBottom: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: BRAND_COLORS.border,
  },
  patientBarItem: {
    fontSize: 8,
    color: BRAND_COLORS.text,
  },
  patientBarLabel: {
    fontFamily: 'Helvetica-Bold',
    color: BRAND_COLORS.dark,
  },
  h1: {
    fontSize: 16,
    fontFamily: 'Helvetica-Bold',
    color: BRAND_COLORS.dark,
    marginBottom: 8,
    marginTop: 4,
  },
  h2: {
    fontSize: 12,
    fontFamily: 'Helvetica-Bold',
    color: BRAND_COLORS.primary,
    marginBottom: 6,
    marginTop: 10,
    paddingBottom: 3,
    borderBottomWidth: 1,
    borderBottomColor: BRAND_COLORS.border,
  },
  h3: {
    fontSize: 10,
    fontFamily: 'Helvetica-Bold',
    color: BRAND_COLORS.text,
    marginBottom: 4,
    marginTop: 8,
  },
  paragraph: {
    fontSize: 9,
    lineHeight: 1.5,
    marginBottom: 6,
    color: BRAND_COLORS.text,
  },
  paragraphWarning: {
    backgroundColor: '#fef3c7',
    padding: 6,
    borderRadius: 3,
    borderLeftWidth: 3,
    borderLeftColor: BRAND_COLORS.warning,
  },
  paragraphCritical: {
    backgroundColor: '#fee2e2',
    padding: 6,
    borderRadius: 3,
    borderLeftWidth: 3,
    borderLeftColor: BRAND_COLORS.critical,
  },
  paragraphSuccess: {
    backgroundColor: '#d1fae5',
    padding: 6,
    borderRadius: 3,
    borderLeftWidth: 3,
    borderLeftColor: BRAND_COLORS.success,
  },
  listItem: {
    flexDirection: 'row',
    marginBottom: 3,
    paddingLeft: 8,
  },
  listBullet: {
    width: 12,
    fontSize: 9,
    color: BRAND_COLORS.primary,
  },
  listText: {
    flex: 1,
    fontSize: 9,
    lineHeight: 1.4,
    color: BRAND_COLORS.text,
  },
  tableContainer: {
    marginBottom: 8,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: BRAND_COLORS.border,
  },
  tableHeaderRow: {
    flexDirection: 'row',
    backgroundColor: BRAND_COLORS.primary,
    borderTopLeftRadius: 3,
    borderTopRightRadius: 3,
  },
  tableHeaderCell: {
    flex: 1,
    padding: 5,
    fontSize: 8,
    fontFamily: 'Helvetica-Bold',
    color: BRAND_COLORS.white,
  },
  tableCell: {
    flex: 1,
    padding: 5,
    fontSize: 8,
    color: BRAND_COLORS.text,
  },
  tableAltRow: {
    backgroundColor: '#f9fafb',
  },
  kvContainer: {
    marginBottom: 6,
  },
  kvRow: {
    flexDirection: 'row',
    paddingVertical: 3,
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  kvLabel: {
    width: '40%',
    fontSize: 9,
    fontFamily: 'Helvetica-Bold',
    color: BRAND_COLORS.dark,
  },
  kvValue: {
    flex: 1,
    fontSize: 9,
    color: BRAND_COLORS.text,
  },
  divider: {
    borderBottomWidth: 1,
    borderBottomColor: BRAND_COLORS.border,
    marginVertical: 8,
  },
  spacer: {
    height: 10,
  },
  signatureBlock: {
    marginTop: 16,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: BRAND_COLORS.border,
  },
  signatureLine: {
    borderBottomWidth: 1,
    borderBottomColor: BRAND_COLORS.text,
    width: 200,
    marginBottom: 4,
    marginTop: 20,
  },
  signatureName: {
    fontSize: 9,
    fontFamily: 'Helvetica-Bold',
    color: BRAND_COLORS.text,
  },
  signatureTitle: {
    fontSize: 8,
    color: BRAND_COLORS.textLight,
  },
  signatureDate: {
    fontSize: 8,
    color: BRAND_COLORS.textLight,
    marginTop: 2,
  },
  imageContainer: {
    marginVertical: 8,
    alignItems: 'center' as const,
  },
  image: {
    maxWidth: '100%',
    borderWidth: 1,
    borderColor: BRAND_COLORS.border,
    borderRadius: 3,
  },
  imageCaption: {
    fontSize: 8,
    fontStyle: 'italic' as const,
    color: BRAND_COLORS.textLight,
    textAlign: 'center' as const,
    marginTop: 4,
  },
});
